import { chromium } from 'playwright';

const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
const errors = [];
page.on('pageerror', (error) => errors.push(String(error)));
page.on('console', (message) => { if (message.type() === 'error') errors.push(message.text()); });
await page.goto('http://127.0.0.1:4173', { waitUntil: 'networkidle' });
await page.selectOption('#template', 'data-structures');
await page.click('[data-action="load-template"]');
if (await page.locator('.prereq-lane .node').count() !== 4) throw new Error('Template prerequisites did not load.');
if (await page.locator('.target-lane .node').count() !== 1) throw new Error('Template target exercise did not load.');
await page.check('.prereq-lane [data-node-field="known"]');
await page.check('.target-lane [data-exercise-field="done"]');
if (!(await page.locator('.checkpoint').getAttribute('class')).includes('achieved')) throw new Error('Checkpoint did not update.');
await page.fill('#new-exercise', 'Compare two traversal orders');
await page.press('#new-exercise', 'Enter');
if (await page.locator('.target-lane .node').count() !== 2) throw new Error('Keyboard add failed.');
await page.reload({ waitUntil: 'networkidle' });
if (await page.locator('.target-lane .node').count() !== 2) throw new Error('Local persistence failed.');
await page.evaluate(() => navigator.serviceWorker.ready);
await page.reload({ waitUntil: 'networkidle' });
await page.context().setOffline(true);
await page.reload({ waitUntil: 'domcontentloaded' });
const offlineMain = await page.locator('#main').count();
if (offlineMain !== 1) throw new Error(`Offline shell failed (main: ${offlineMain}).`);
await page.context().setOffline(false);
await page.goto('http://127.0.0.1:4173/privacy', { waitUntil: 'networkidle' });
if (await page.locator('h1').count() !== 1) throw new Error('Privacy route has invalid h1 count.');
await browser.close();
if (errors.length) throw new Error(`Browser errors: ${errors.join('; ')}`);
console.log('Browser smoke: template, diagnostics, target completion, keyboard add, persistence, offline shell, and legal route passed.');
